name: fmt-build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt -- --check
    - name: build
      run: cargo build
    - name: test
      run: cargo test